### PR TITLE
Workflow updates for Darwin: add SDL to release builds; enable cross-compile in makefiles; add cross-compile & universal executables to release builds ...

### PR DESCRIPTION
**Pull request by fghalasz**
Also update workflows to latest action versions and update handling of GITHIUB_ENV to get rid of deprecated set-output.

This is a resubmit of closed PR#469.  Changes from that PR include rebased branch onto latest master; added support for SDL in release builds for Darwin.

### CODE REVIEW

**Review by nbriggs — APPROVED** [review]
This looks OK to me.  I don't know enough about the workflow to make any significant comments on it.   The effect of using "makeright x" then "makeright sdl" that you'll end up with an "lde" that can only start an "ldex".  Currently, the only way to get an "lde" that can start either one (depending on the "-display" option) is to build using CMake.

**Comment by masinter** [comment]
> This looks OK to me. I don't know enough about the workflow to make any significant comments on it. The effect of using "makeright x" then "makeright sdl" that you'll end up with an "lde" that can only start an "ldex". Currently, the only way to get an "lde" that can start either one (depending on the "-display" option) is to build using CMake.

should this be a new (low priority) issue?

**Comment by nbriggs** [comment]
Fixing the "makeright" so you can do both?  It would add another "display" target.   Not sure that it's worth it when you can compile the whole thing, making universal binaries, with both X11 and SDL2 by doing:
```
cd maiko
mkdir build
cmake .. -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DMAIKO_DISPLAY_SDL=ON -DMAIKO_DISPLAY_X11=ON
```
which will leave you with lde, ldex, ldesdl (I don't have it doing ldeinit yet) in the build directory.

**Comment by fghalasz** [comment]
Ok.  Switched over build of lde, ldex and ldesdl to cmake.,   Left ldeinit to be made by makeright init.

Also changed Xquartz to be loaded by installer of XQuartz-2.8.5.pkg rather than via homebrew.  And removed all the xlibs that are preinstalled on MacOS runners cause they were interfering with cross-compile of aarch64 on x86_64 runners.

**Comment by nbriggs** [comment]
Nice.  I've got a CMakeLists.txt that defines how to also compile ldeinit when you have X11 enabled (I can't do an SDL based ldeinit).  I'll probably put the PR in on Friday.

**Pull request merged**
