### PR TITLE
The SYSVONLY flag is no longer used or needed.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
Welcome to the world of being mostly POSIX!

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This will be turned into a normal PR once #152 lands.

**Comment by waywardmonkeys** [comment]
This should be ready to go now.

**Review by nbriggs — APPROVED** [review]
LGTM

**Review by nbriggs — APPROVED** [review]
LGTM

**Pull request merged**
