### PR TITLE
Cleanup uraid

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Review by blakemcbride — APPROVED** [review]
Good cleanups!

**Review by nbriggs — COMMENTED** [review]
GetDTD and GetTypeNumber are macros.  These functions are provided so that when you're in the debugger (as you likely will need to be, if you end up in uraid) you can use them to print  information about the things you're debugging.

I'd prefer not to remove these.

**Comment by waywardmonkeys** [comment]
@nbriggs Updated to remove that commit that removed those functions.

**Comment by waywardmonkeys** [comment]
@nbriggs I addressed your comments. Could this please go in to get rid of these warnings?

**Comment by nbriggs** [comment]
Yeah, sorry, busy today.

**Pull request merged**
