### PR TITLE
X*.h headers weren't cleaned up after renaming and merging.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
* Check.h, Stipple.h, XCursors.h, XWaitCur.h, Xcursdef.h,
  Xdefcur.h, and Xicon.h were combined into xbitmaps.h.
* Xdisplay.h is not used and the contents are in MyWindow.h, which
  is used.
* XVersion.h and Xdeflt.h became xdefs.h. Remove 2 stragglers
  that were still including XVersion.h.

### CODE REVIEW

**Comment by nbriggs** [comment]
Do you want to address these potential fixups at the same time?
```
grep -e 'X[a-z]' makefile-tail
	$(INCDIR)MyWindow.h $(INCDIR)Xbitblt.h
	$(INCDIR)MyWindow.h $(INCDIR)Xbitblt.h
$(OBJECTDIR)Xevinit.o : $(SRCDIR)Xevinit.c  $(REQUIRED-INCS) $(INCDIR)xdefs.h \
	$(CC) $(RFLAGS) $(SRCDIR)Xevinit.c -o $(OBJECTDIR)Xevinit$(OEXT)
$(OBJECTDIR)Xkbdmus.o : $(SRCDIR)Xkbdmus.c  $(REQUIRED-INCS) $(INCDIR)lispemul.h \
	$(CC) $(RFLAGS) $(SRCDIR)Xkbdmus.c -o $(OBJECTDIR)Xkbdmus$(OEXT)
$(OBJECTDIR)Xlspwin.o : $(SRCDIR)Xlspwin.c  $(REQUIRED-INCS) $(INCDIR)xdefs.h \
	$(INCDIR)MyWindow.h $(INCDIR)Xdeflt.h
	$(CC) $(RFLAGS) $(SRCDIR)Xlspwin.c -o $(OBJECTDIR)Xlspwin$(OEXT)
$(OBJECTDIR)Xbbt.o : $(SRCDIR)Xbbt.c  $(REQUIRED-INCS) $(INCDIR)xdefs.h \
	$(CC) $(RFLAGS) $(SRCDIR)Xbbt.c -o $(OBJECTDIR)Xbbt$(OEXT)
$(OBJECTDIR)LispXdisplay.o : $(SRCDIR)LispXdisplay.c  $(REQUIRED-INCS) $(INCDIR)lispemul.h \
	$(INCDIR)xdefs.h $(INCDIR)MyWindow.h $(INCDIR)Xbitblt.h
	$(CC) $(RFLAGS) $(SRCDIR)LispXdisplay.c -o $(OBJECTDIR)LispXdisplay$(OEXT)
$(OBJECTDIR)Xkbd.o : $(SRCDIR)Xkbd.c  $(REQUIRED-INCS) $(INCDIR)xdefs.h \
	$(CC) $(RFLAGS) $(SRCDIR)Xkbd.c -o $(OBJECTDIR)Xkbd$(OEXT)
$(OBJECTDIR)Xmkicon.o : $(SRCDIR)Xmkicon.c  $(REQUIRED-INCS) $(INCDIR)xdefs.h \
	$(CC) $(RFLAGS) $(SRCDIR)Xmkicon.c -o $(OBJECTDIR)Xmkicon$(OEXT)
$(OBJECTDIR)Xopendsp.o : $(SRCDIR)Xopendsp.c  $(REQUIRED-INCS) $(INCDIR)lispemul.h \
	$(CC) $(RFLAGS) $(SRCDIR)Xopendsp.c -o $(OBJECTDIR)Xopendsp$(OEXT)
$(OBJECTDIR)Xrdopt.o : $(SRCDIR)Xrdopt.c  $(REQUIRED-INCS) $(INCDIR)Xdeflt.h
	$(CC) $(RFLAGS) $(SRCDIR)Xrdopt.c -o $(OBJECTDIR)Xrdopt$(OEXT)
$(OBJECTDIR)Xreconf.o : $(SRCDIR)Xreconf.c  $(REQUIRED-INCS) \
	$(CC) $(RFLAGS) $(SRCDIR)Xreconf.c -o $(OBJECTDIR)Xreconf$(OEXT)
$(OBJECTDIR)Xscrolb.o : $(SRCDIR)Xscrolb.c  $(REQUIRED-INCS) $(INCDIR)xdefs.h \
	$(CC) $(RFLAGS) $(SRCDIR)Xscrolb.c -o $(OBJECTDIR)Xscrolb$(OEXT)
$(OBJECTDIR)Xsubwin.o : $(SRCDIR)Xsubwin.c  $(REQUIRED-INCS) $(INCDIR)xdefs.h \
	$(CC) $(RFLAGS) $(SRCDIR)Xsubwin.c -o $(OBJECTDIR)Xsubwin$(OEXT)
$(OBJECTDIR)Xcolor.o : $(SRCDIR)Xcolor.c  $(REQUIRED-INCS) $(INCDIR)xdefs.h \
	$(CC) $(RFLAGS) $(SRCDIR)Xcolor.c -o $(OBJECTDIR)Xcolor$(OEXT)
$(OBJECTDIR)Xwinman.o : $(SRCDIR)Xwinman.c  $(REQUIRED-INCS) $(INCDIR)xdefs.h \
	$(CC) $(RFLAGS) $(SRCDIR)Xwinman.c -o $(OBJECTDIR)Xwinman$(OEXT)
```

**Comment by waywardmonkeys** [comment]
In this case, no. Almost all of those files don’t actually exist any longer and I have a plan to remove all non-existing files from the `makefile-tail` at once.

**Comment by nbriggs** [comment]
Their non-existance was what I had observed.  I'll go ahead and merge this branch as is then.

**Review by nbriggs — APPROVED** [review]
LGTM.

**Pull request merged**
