### PR TITLE
Remove remnants of valloc workarounds

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
valloc is page-aligned but isn't commonly used these days. But maybe we'd like to align this allocation in some other way? Or it isn't important?

**Comment by nbriggs** [comment]
Not sure about this one.   Every Unix system we compile for seems to support valloc(), and it makes debugging easier when the Lisp pages are aligned with the system pages.

**Comment by waywardmonkeys** [comment]
Okay, I'll modify this PR then ... one moment.

**Comment by nbriggs** [comment]
We could go with posix_memalign() if it's support on all the systems we support (and I think that now, it is)

**Comment by waywardmonkeys** [comment]
Looks like `valloc` is now more standard than it used to be, so instead of removing it, I have now removed the workarounds for it not being everywhere.

**Pull request merged**
