### PR TITLE
Correct signal handler arguments

### PR DESCRIPTION
**Pull request by blakemcbride**

### CODE REVIEW

**Comment by nbriggs** [comment]
I think we'll probably move to use POSIX `sigaction()` for the handlers, but we need to survey the implementations on some different systems first.

**Comment by blakemcbride** [comment]
Until then, this corrects what we have.

**Comment by waywardmonkeys** [comment]
I'm hoping to move to `sigaction` this week.

**Comment by waywardmonkeys** [comment]
See PR #190.

**Comment by nbriggs** [comment]
Closed, superseded by move to POSIX signal handling.

**Pull request closed without merging**
