### PR TITLE
Pointer math correction

### PR DESCRIPTION
**Pull request by blakemcbride**

### CODE REVIEW

**Review by waywardmonkeys — CHANGES_REQUESTED** [review]
I was working on a similar patch ... but in that, I'd changed the types of `len`, and `diff` and such to `size_t`. Would you mind doing the same here?

**Comment by blakemcbride** [comment]
Done

**Review by waywardmonkeys — APPROVED** [review]
LGTM

**Review by nbriggs — APPROVED** [review]
LGTM

**Pull request merged**
