### PR TITLE
Switch from ioctl/FIONBIO to fcntl/O_NONBLOCK.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This is only built on Solaris, so if you could give it a try there, I'd appreciate it!

**Review by nbriggs — APPROVED** [review]
Compiles OK on Solaris 11.4/sparc.  I don't have an RPC based test case to check operation.

**Comment by waywardmonkeys** [comment]
@nbriggs We can probably bring back that `BSD_COMP` removal patch then!

**Comment by nbriggs** [comment]
@waywardmonkeys Yes we can -- I've just verified that it compiles cleanly without it.

**Pull request merged**
