### PR TITLE
Remove platform support for Apollo/Domain.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Review by nbriggs — COMMENTED** [review]
You're not going after the
```
# This is to make the %$#@! Apollo cc happy
OEXT = .o
```
that's scattered through almost all the bin/make* files?

**Comment by waywardmonkeys** [comment]
I wanted to do that separately!

**Comment by waywardmonkeys** [comment]
But I could do it as a second commit in this PR. It was confusing as the Apollo code was doing the same as everyone else here.

**Comment by nbriggs** [comment]
A separate PR would be fine too, along with thinking about whether we actually need any OEXT -- aren't all platforms using .o and not parameterizing it at all?

**Comment by nbriggs** [comment]
I'll go ahead and merge this as is.

**Pull request merged**
