### PR TITLE
osmsg now uses MAIKO_HANDLE_CONSOLE_MESSAGES

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This was checking that neither `DOS` nor `XWINDOW` were defined,
but this needs a more specific flag for this feature so that it
doesn't get enabled when `!DOS && !XWINDOW`.

### CODE REVIEW

**Review by nbriggs — APPROVED** [review]
LGTM.  The only time that it makes sense to have Lisp take the console log messages is when it is running on the raw framebuffer device that would otherwise be the system console, and it needs to capture logging messages that would otherwise print there, so that they don't disrupt the screen image and can be retrieved and played back into a Lisp window.

**Comment by waywardmonkeys** [comment]
Yep, but if someone were hypothetically writing a different display backend, then it gets annoying when things don't compile without one of `XWINDOW` or `DOS` or `SUNDISPLAY`. :) And I didn't want to tie that functionality to `SUNDISPLAY` ...

**Comment by waywardmonkeys** [comment]
(And that code should be updated to use `termio` anyway...)

**Comment by nbriggs** [comment]
Yeah, I wasn't suggesting that it should be any different that what you did, just throwing in a bit of the rationale for why it existed at all.

**Comment by masinter** [comment]
what does URAID use except termio?

**Comment by waywardmonkeys** [comment]
@masinter The code in `osmsg.c` is still using pre-`termio` `ioctl` calls from the `sgtty` days. That code isn't used, so it isn't a priority to update. This is unrelated to URAID. URAID uses `stdio.h`, no `termio` calls.

**Pull request merged**
