### PR TITLE
Don't close a file that hasn't been opened (2)

### PR DESCRIPTION
**Pull request by blakemcbride**

### CODE REVIEW

**Review by nbriggs — APPROVED** [review]
LGTM

**Review by nbriggs — COMMENTED** [review]
Do we have a test case for this?  This is going to change the value that is returned in `Lisp_errno` to ENOENT from whatever might have been returned from the bogus `close()`, which might have been EBADF, or 0.  I haven't traced through the Lisp code to see what effect, if any, this would have.

**Comment by waywardmonkeys** [comment]
(Copying comments from the other version of the PR that got closed.)

Looks good to me. I suspect this was copied from a block below where maintain_version is called, and at that point, fd does have a valid value.

It is worth noting that this wouldn't have been an issue with C99 if we were declaring variables closer to where they're actually valid rather than C89-style at the top of the function. :)

**Comment by waywardmonkeys** [comment]
This was also flagged by `clang-tidy`, but I hadn't looked at it yet:

```
/home/bruce/Development/maiko/src/dsk.c:456:26: warning: 1st function call argument is an uninitialized value [clang-analyzer-core.CallAndMessage]
          TIMEOUT(rval = close(fd));
                         ^
../inc/timeout.h:31:14: note: expanded from macro 'TIMEOUT'
    INTRSAFE(exp);                      \
             ^
../inc/timeout.h:67:22: note: expanded from macro 'INTRSAFE'
  do {} while ((int)(exp) == -1 && errno == EINTR)
                     ^
/home/bruce/Development/maiko/src/dsk.c:225:34: note: 'fd' declared without an initial value
  register int fatp, dskp, rval, fd, link_check_flg, flags, *bufp;
                                 ^
/home/bruce/Development/maiko/src/dsk.c:232:3: note: Assuming the condition is false
  ERRSETJMP(NIL);
  ^
../inc/timeout.h:49:8: note: expanded from macro 'ERRSETJMP'
    if(setjmp(jmpbuf) != 0)                             \
       ^
/usr/include/setjmp.h:62:21: note: expanded from macro 'setjmp'
#define setjmp(env)     _setjmp (env)
                        ^
/home/bruce/Development/maiko/src/dsk.c:232:3: note: Taking false branch
  ERRSETJMP(NIL);
  ^
../inc/timeout.h:49:5: note: expanded from macro 'ERRSETJMP'
    if(setjmp(jmpbuf) != 0)                             \
    ^
/home/bruce/Development/maiko/src/dsk.c:235:3: note: Control jumps to 'case 68:'  at line 235
  LispStringLength(args[0], rval, fatp);
  ^
../inc/locfile.h:157:5: note: expanded from macro 'LispStringLength'
    switch(lf_arrayp->typenumber)                                               \
    ^
/home/bruce/Development/maiko/src/dsk.c:235:3: note:  Execution continues on line 242
  LispStringLength(args[0], rval, fatp);
  ^
../inc/locfile.h:167:3: note: expanded from macro 'LispStringLength'
                break;                                                  \
                ^
/home/bruce/Development/maiko/src/dsk.c:242:10: note: 'fatp' is 1
  rval = fatp ? rval + 4 + 1 : rval + 2 + 1;
         ^
/home/bruce/Development/maiko/src/dsk.c:242:10: note: '?' condition is true
/home/bruce/Development/maiko/src/dsk.c:244:7: note: Assuming the condition is false
  if (rval > MAXPATHLEN + 5) FileNameTooLong(NIL);
      ^
/home/bruce/Development/maiko/src/dsk.c:244:3: note: Taking false branch
  if (rval > MAXPATHLEN + 5) FileNameTooLong(NIL);
  ^
/home/bruce/Development/maiko/src/dsk.c:246:40: note: Assuming 4096 is > field 'fillpointer'
  LispStringToCString(args[0], lfname, MAXPATHLEN);
                                       ^
/usr/include/x86_64-linux-gnu/sys/param.h:48:21: note: expanded from macro 'MAXPATHLEN'
# define MAXPATHLEN     PATH_MAX
                        ^
/usr/include/linux/limits.h:13:25: note: expanded from macro 'PATH_MAX'
#define PATH_MAX        4096    /* # chars in a path name including nul */
                        ^
../inc/locfile.h:118:21: note: expanded from macro 'LispStringToCString'
    lf_length = min(MaxLen, lf_arrayp->fillpointer);                    \
                    ^
../inc/locfile.h:191:21: note: expanded from macro 'min'
#define min(a, b) ((a <= b)?a:b)
                    ^
/home/bruce/Development/maiko/src/dsk.c:246:3: note: '?' condition is false
  LispStringToCString(args[0], lfname, MAXPATHLEN);
  ^
../inc/locfile.h:118:17: note: expanded from macro 'LispStringToCString'
    lf_length = min(MaxLen, lf_arrayp->fillpointer);                    \
                ^
../inc/locfile.h:191:20: note: expanded from macro 'min'
#define min(a, b) ((a <= b)?a:b)
                   ^
/home/bruce/Development/maiko/src/dsk.c:246:3: note: Control jumps to 'case 68:'  at line 246
  LispStringToCString(args[0], lfname, MAXPATHLEN);
  ^
../inc/locfile.h:119:5: note: expanded from macro 'LispStringToCString'
    switch(lf_arrayp->typenumber)                                               \
    ^
/home/bruce/Development/maiko/src/dsk.c:246:3: note: Assuming 'lf_ii' is >= 'lf_length'
  LispStringToCString(args[0], lfname, MAXPATHLEN);
  ^
../inc/locfile.h:131:23: note: expanded from macro 'LispStringToCString'
                for(lf_ii=0,lf_dp=C;lf_ii<(lf_length);lf_ii++,lf_sbase++)  \
                                    ^
/home/bruce/Development/maiko/src/dsk.c:246:3: note: Loop condition is false. Execution continues on line 246
  LispStringToCString(args[0], lfname, MAXPATHLEN);
  ^
../inc/locfile.h:131:3: note: expanded from macro 'LispStringToCString'
                for(lf_ii=0,lf_dp=C;lf_ii<(lf_length);lf_ii++,lf_sbase++)  \
                ^
/home/bruce/Development/maiko/src/dsk.c:246:3: note:  Execution continues on line 251
  LispStringToCString(args[0], lfname, MAXPATHLEN);
  ^
../inc/locfile.h:134:3: note: expanded from macro 'LispStringToCString'
                break;                                                  \
                ^
/home/bruce/Development/maiko/src/dsk.c:253:3: note: Assuming the condition is false
  UPCASE(host);
  ^
../inc/locfile.h:212:20: note: expanded from macro 'UPCASE'
        for(lf_cp = name; *lf_cp!='\0'; ++lf_cp)                                \
                          ^
/home/bruce/Development/maiko/src/dsk.c:253:3: note: Loop condition is false. Execution continues on line 255
  UPCASE(host);
  ^
../inc/locfile.h:212:2: note: expanded from macro 'UPCASE'
        for(lf_cp = name; *lf_cp!='\0'; ++lf_cp)                                \
        ^
/home/bruce/Development/maiko/src/dsk.c:255:7: note: Assuming the condition is true
  if (strcmp(host, "DSK") == 0)
      ^
/home/bruce/Development/maiko/src/dsk.c:255:3: note: Taking true branch
  if (strcmp(host, "DSK") == 0)
  ^
/home/bruce/Development/maiko/src/dsk.c:280:3: note: Control jumps to 'case 917507:'  at line 305
  switch (args[1]) {
  ^
/home/bruce/Development/maiko/src/dsk.c:313:7: note: Control jumps to 'case 917507:'  at line 349
      switch (args[2]) {
      ^
/home/bruce/Development/maiko/src/dsk.c:351:15: note: 'dskp' is 1
          if (dskp) {
              ^
/home/bruce/Development/maiko/src/dsk.c:351:11: note: Taking true branch
          if (dskp) {
          ^
/home/bruce/Development/maiko/src/dsk.c:353:17: note: Assuming the condition is false
            if (make_directory(dir) == 0) return (NIL);
                ^
/home/bruce/Development/maiko/src/dsk.c:353:13: note: Taking false branch
            if (make_directory(dir) == 0) return (NIL);
            ^
/home/bruce/Development/maiko/src/dsk.c:356:11: note:  Execution continues on line 358
          break;
          ^
/home/bruce/Development/maiko/src/dsk.c:358:7: note:  Execution continues on line 380
      break;
      ^
/home/bruce/Development/maiko/src/dsk.c:380:7: note: 'dskp' is 1
  if (dskp) {
      ^
/home/bruce/Development/maiko/src/dsk.c:380:3: note: Taking true branch
  if (dskp) {
  ^
/home/bruce/Development/maiko/src/dsk.c:381:9: note: Assuming the condition is false
    if (unpack_filename(file, dir, name, ver, 1) == 0) return (NIL);
        ^
/home/bruce/Development/maiko/src/dsk.c:381:5: note: Taking false branch
    if (unpack_filename(file, dir, name, ver, 1) == 0) return (NIL);
    ^
/home/bruce/Development/maiko/src/dsk.c:382:9: note: Assuming the condition is false
    if (true_name(dir) != -1) return (0);
        ^
/home/bruce/Development/maiko/src/dsk.c:382:5: note: Taking false branch
    if (true_name(dir) != -1) return (0);
    ^
/home/bruce/Development/maiko/src/dsk.c:383:9: note: Assuming the condition is false
    if (get_version_array(dir, name, VersionArray, &VArrayInfo) == 0) return (NIL);
        ^
/home/bruce/Development/maiko/src/dsk.c:383:5: note: Taking false branch
    if (get_version_array(dir, name, VersionArray, &VArrayInfo) == 0) return (NIL);
    ^
/home/bruce/Development/maiko/src/dsk.c:384:5: note: Assuming the condition is false
    ConcNameAndVersion(name, ver, file);
    ^
../inc/locfile.h:482:6: note: expanded from macro 'ConcNameAndVersion'
        if (*ver != '\0') {                                             \
            ^
/home/bruce/Development/maiko/src/dsk.c:384:5: note: Taking false branch
    ConcNameAndVersion(name, ver, file);
    ^
../inc/locfile.h:482:2: note: expanded from macro 'ConcNameAndVersion'
        if (*ver != '\0') {                                             \
        ^
/home/bruce/Development/maiko/src/dsk.c:386:5: note: Control jumps to 'case 917507:'  at line 399
    switch (args[1]) {
    ^
/home/bruce/Development/maiko/src/dsk.c:400:13: note: Assuming the condition is false
        if (get_old_new(dir, VersionArray, file, name) == 0) return (NIL);
            ^
/home/bruce/Development/maiko/src/dsk.c:400:9: note: Taking false branch
        if (get_old_new(dir, VersionArray, file, name) == 0) return (NIL);
        ^
/home/bruce/Development/maiko/src/dsk.c:401:9: note:  Execution continues on line 410
        break;
        ^
/home/bruce/Development/maiko/src/dsk.c:410:7: note: 'dskp' is 1
  if (dskp) {
      ^
/home/bruce/Development/maiko/src/dsk.c:410:3: note: Taking true branch
  if (dskp) {
  ^
/home/bruce/Development/maiko/src/dsk.c:411:5: note: Assuming the condition is false
    TIMEOUT(rval = stat(file, &sbuf));
    ^
../inc/timeout.h:31:5: note: expanded from macro 'TIMEOUT'
    INTRSAFE(exp);                      \
    ^
../inc/timeout.h:67:16: note: expanded from macro 'INTRSAFE'
  do {} while ((int)(exp) == -1 && errno == EINTR)
               ^
/home/bruce/Development/maiko/src/dsk.c:411:5: note: Left side of '&&' is false
    TIMEOUT(rval = stat(file, &sbuf));
    ^
../inc/timeout.h:31:5: note: expanded from macro 'TIMEOUT'
    INTRSAFE(exp);                      \
    ^
../inc/timeout.h:67:33: note: expanded from macro 'INTRSAFE'
  do {} while ((int)(exp) == -1 && errno == EINTR)
                                ^
/home/bruce/Development/maiko/src/dsk.c:411:5: note: Loop condition is false.  Exiting loop
    TIMEOUT(rval = stat(file, &sbuf));
    ^
../inc/timeout.h:31:5: note: expanded from macro 'TIMEOUT'
    INTRSAFE(exp);                      \
    ^
../inc/timeout.h:67:3: note: expanded from macro 'INTRSAFE'
  do {} while ((int)(exp) == -1 && errno == EINTR)
  ^
/home/bruce/Development/maiko/src/dsk.c:412:9: note: Assuming 'rval' is equal to 0
    if (rval == 0) {
        ^
/home/bruce/Development/maiko/src/dsk.c:412:5: note: Taking true branch
    if (rval == 0) {
    ^
/home/bruce/Development/maiko/src/dsk.c:413:11: note: Assuming the condition is false
      if ((sbuf.st_mode & S_IFMT) != S_IFREG) {
          ^
/home/bruce/Development/maiko/src/dsk.c:413:7: note: Taking false branch
      if ((sbuf.st_mode & S_IFMT) != S_IFREG) {
      ^
/home/bruce/Development/maiko/src/dsk.c:434:7: note: 'dskp' is 1
  if (dskp && link_check_flg) {
      ^
/home/bruce/Development/maiko/src/dsk.c:434:7: note: Left side of '&&' is true
/home/bruce/Development/maiko/src/dsk.c:434:15: note: 'link_check_flg' is 1
  if (dskp && link_check_flg) {
              ^
/home/bruce/Development/maiko/src/dsk.c:434:3: note: Taking true branch
  if (dskp && link_check_flg) {
  ^
/home/bruce/Development/maiko/src/dsk.c:448:5: note: Assuming the condition is true
    TIMEOUT(rval = access(file, F_OK));
    ^
../inc/timeout.h:31:5: note: expanded from macro 'TIMEOUT'
    INTRSAFE(exp);                      \
    ^
../inc/timeout.h:67:16: note: expanded from macro 'INTRSAFE'
  do {} while ((int)(exp) == -1 && errno == EINTR)
               ^
/home/bruce/Development/maiko/src/dsk.c:448:5: note: Left side of '&&' is true
    TIMEOUT(rval = access(file, F_OK));
    ^
../inc/timeout.h:31:5: note: expanded from macro 'TIMEOUT'
    INTRSAFE(exp);                      \
    ^
../inc/timeout.h:67:16: note: expanded from macro 'INTRSAFE'
  do {} while ((int)(exp) == -1 && errno == EINTR)
               ^
/home/bruce/Development/maiko/src/dsk.c:448:5: note: Assuming the condition is false
    TIMEOUT(rval = access(file, F_OK));
    ^
../inc/timeout.h:31:5: note: expanded from macro 'TIMEOUT'
    INTRSAFE(exp);                      \
    ^
../inc/timeout.h:67:36: note: expanded from macro 'INTRSAFE'
  do {} while ((int)(exp) == -1 && errno == EINTR)
                                   ^
/usr/include/errno.h:38:16: note: expanded from macro 'errno'
# define errno (*__errno_location ())
               ^
/home/bruce/Development/maiko/src/dsk.c:448:5: note: Loop condition is false.  Exiting loop
    TIMEOUT(rval = access(file, F_OK));
    ^
../inc/timeout.h:31:5: note: expanded from macro 'TIMEOUT'
    INTRSAFE(exp);                      \
    ^
../inc/timeout.h:67:3: note: expanded from macro 'INTRSAFE'
  do {} while ((int)(exp) == -1 && errno == EINTR)
  ^
/home/bruce/Development/maiko/src/dsk.c:449:5: note: Taking true branch
    if (rval == -1) {
    ^
/home/bruce/Development/maiko/src/dsk.c:450:11: note: Assuming the condition is true
      if (errno == ENOENT) {
          ^
/usr/include/errno.h:38:16: note: expanded from macro 'errno'
# define errno (*__errno_location ())
               ^
/home/bruce/Development/maiko/src/dsk.c:450:7: note: Taking true branch
      if (errno == ENOENT) {
      ^
/home/bruce/Development/maiko/src/dsk.c:455:13: note: Assuming the condition is true
        if (maintain_version(file, (FileName *)NULL, 1) == 0) {
            ^
/home/bruce/Development/maiko/src/dsk.c:455:9: note: Taking true branch
        if (maintain_version(file, (FileName *)NULL, 1) == 0) {
        ^
/home/bruce/Development/maiko/src/dsk.c:456:26: note: 1st function call argument is an uninitialized value
          TIMEOUT(rval = close(fd));
                         ^
../inc/timeout.h:31:14: note: expanded from macro 'TIMEOUT'
    INTRSAFE(exp);                      \
             ^
../inc/timeout.h:67:22: note: expanded from macro 'INTRSAFE'
  do {} while ((int)(exp) == -1 && errno == EINTR)
                     ^
```

**Comment by nbriggs** [comment]
While clang-tidy can be quite useful, it frequently proposes fixes that aren't relevant because the static analysis is just that.

**Comment by waywardmonkeys** [comment]
I was pointing out that it had identified this particular bug. :)

**Comment by nbriggs** [comment]
Yes, indeed it did.  There are another 110 "problems" that it reports to triage too.  I have been using "scan-build" from clang-9 to run the whole compilation through the analyzer.  Which version are you using, and do you have a count of what it's reporting?

**Comment by blakemcbride** [comment]
In terms maiko, I do not know how to do a "test case".

**Review by masinter — CHANGES_REQUESTED** [review]
walking through the code, it doesn't look like fd is set at this point.
So "Don't call close on uninitialized variable" might be a better name for this PR.
but this still begs the question of where errno is set. If it isn't the failure code for a close on an unopened file, what is it set to? 
https://github.com/Interlisp/medley/issues/20 seems like it involves the same code.

**Pull request merged**
