### PR TITLE
Experiment yield subr

### PR DESCRIPTION
**Pull request by masinter**
as discussed

### CODE REVIEW

**Comment by nbriggs** [comment]
This is a mess and won't build.  It needs to be rebased on the current master, I think.

**Comment by waywardmonkeys** [comment]
I'd like to hold off on this for a week (but keep it open).

The alternate display code that I'm working on will need something of this sort as well as it is using OpenGL (or Metal on macOS) (or WebGL in the browser), and it needs the ability to do a render periodically.

Also, running in the browser means that we can't have an infinite loop like we do now for `dispatch`.

**Comment by masinter** [comment]
https://github.com/Interlisp/medley/pull/254#pullrequestreview-609197575

**Comment by nbriggs** [comment]
What has #254 (unixprint) got to do with this?

**Comment by nbriggs** [comment]
I think that the Link above (medley 254) is unrelated to this.

**Comment by masinter** [comment]
it's been a month. I run with this always.

**Comment by masinter** [comment]
FYI This PR was merged and the merge reverted, but it still shows up as Merged.

**Pull request merged**
