### PR TITLE
Remove OCR code.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This is very dated code that assumes there's a `/dev/ocr0`.

I'm not sure what system this was for, but it doesn't appear to
be one that exists currently.

Discussed in interlisp/medley#126.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
There's a lot of very old signal handling code in this file among other things, so I keep seeing it when grepping.

**Review by nbriggs — APPROVED** [review]
LGTM.

**Comment by nbriggs** [comment]
I'm guessing this code hooked up to a SCSI connected OCR scanner, probably a Japanese office device.
The code isn't remotely interesting today except as a reference for how one might add call-outs to slow external devices.
I think the code can be deleted.

**Comment by nbriggs** [comment]
Hi... @masinter you added yourself as a reviewer, did you want to add something to the review comments?

**Review by masinter — APPROVED** [review]
sorry, i was looking for a way to indicate approval

**Pull request merged**
